name: perinuclear_analysis
channels:
  - conda-forge
  - defaults
  - nvidia  # For CUDA support

dependencies:
  # Core Python
  - python>=3.9
  
  # Core scientific computing
  - numpy>=1.20.0
  - scipy>=1.7.0
  - scikit-image>=0.19.0
  - matplotlib>=3.5.0
  - pillow>=9.0.0
  
  # Image I/O and processing
  - tifffile>=2023.7.10
  - nd2reader>=3.3.0
  
  # CUDA acceleration (optional - will be available if CUDA is installed)
  - cupy  # GPU-accelerated NumPy
  
  # Development tools
  - jupyter
  - jupyterlab
  - ipykernel
  
  # Data analysis (for future phases)
  - pandas>=1.4.0
  - seaborn>=0.11.0
  
  # Testing and development
  - pytest>=7.0.0
  - pytest-cov>=3.0.0
  - black>=22.0.0
  - flake8>=4.0.0
  
  # Documentation
  - sphinx>=4.5.0
  - sphinx-rtd-theme
  
  # Pip dependencies (for packages not available in conda)
  - pip
  - pip:
    # Add any pip-only dependencies here
    # - some-pip-only-package>=1.0.0
